### ISSUE TITLE
Chili pepper texture missing for age 1

### ISSUE THREAD

**Issue by AutoRunFail** [ianm1647/expandeddelight#11]
Hello!  The chili pepper plant is missing it's texture on age 1. All the other ages are fine, it's just age 1 that is missing it's texture. 

Version: Expanded Delight 0.1.9 on 1.18.2 Minecraft

Update:  Found the exact error message referencing this :

[Worker-Main-2/WARN]: Unable to load model: 'expandeddelight:block/chili_pepper_crop_stage1' referenced from: expandeddelight:chili_pepper_crop#age=0: java.io.FileNotFoundException: expandeddelight:models/block/chili_pepper_crop_stage1.json

**Comment by Geethebluesky** [comment]
Getting the same error on 1.18.2.

**Comment by Geethebluesky** [comment]
@ianm1647 The problem here is your file is named "chil**L**_pepper_crop_stage1.json" instead of chili with a final i :)

**Comment by faeldray** [comment]
It looks like this was fixed for the 1.19 version but not the 1.18 version
![image](https://user-images.githubusercontent.com/967709/198184782-251c117b-a5c0-4c63-9e5e-b25c02146d96.png)
