### ISSUE TITLE
[1.19][Bug] Crash with Roughly Enough Items mod

### ISSUE THREAD

**Issue by AubriTheHuman** [ianm1647/expandeddelight#13]
I dont exactly know what causes it, but this is a decently major issue. It seems like the mod hasnt updated REI mappings in 1.19 if I had to guess. Happens in latest release. Also does not produce a crash report, but I think that is more of a REI issue. This only seems to happen when running a dedicated server, and does not occur when loading or creating a single player world.

Log snippet pastebin : https://pastebin.com/hzRxjF6w
Full log pastebin: https://pastebin.com/XNNMwHpZ

**Comment by ianm1647** [comment]
weird, because i have the entry point set to rei_common

**Comment by ianm1647** [comment]
im setting it to rei_client instead hoping that will fix the problem, that way it doesnt have to load both serverside and clientside

**Comment by Geartwo** [comment]
I tested it: Startup -> OK, THX
