### ISSUE TITLE
expanded delight crashing minecraft

### ISSUE THREAD

**Issue by WPeanuts** [ianm1647/expandeddelight#16]
" The game crashed whilst initializing game 
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'expandeddelight'! "

I've been using it for a while and just got some new mods so I guess the mods could the problem?

**Comment by WPeanuts** [comment]
I can add the exit code and crash report of that'll help

**Comment by ianm1647** [comment]
update your mod

**Comment by WPeanuts** [comment]
its updated still same thing but ill just uninstall
