### ISSUE TITLE
Crashing at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [ianm1647/expandeddelight#22]
Fabric: 0.14.9
Minecraft: 1.18.2

https://bytebin.lucko.me/UrNyqnoHl5

**Comment by tessagithub** [comment]
Hi, I am having the exact same error. Did you manage to find a solution? Bit lost. Thanks!

**Comment by 0DeltaWaves** [comment]
Same problem on 1.19

**Comment by ianm1647** [comment]
> Same problem on 1.19

this is fixed for 1.19, not 1.18.2 yet, i’m trying to find time

**Comment by TheButterbrotMan** [comment]
Any news? Tempfix?

**Comment by KirboSoftware** [comment]
I've made a PR to apply that hotfix @TheButterbrotMan , so should be fine if @ianm1647  accepts the PR or does the changes himself/herself.

**Comment by ianm1647** [comment]
im updating the mod currently
should be out in the next hour
