### ISSUE TITLE
Cheese wheel can't be sliced on cutting board (issue is very easily fixed)

### ISSUE THREAD

**Issue by viedemarli** [ianm1647/expandeddelight#23]
Fabric: 0.14.9
Minecraft: 1.19
Expanded Delight: 0.2.2 

I didn't see this in any of the open or closed issues, but the line in the recipe for cheese_slice.json for which tools are needed to cut the cheese wheels needs to be changed from "farmersdelight:tools/knives" to "c:tools/knives"

Changing it to the latter version fixed the issue completely!!

**Comment by ianm1647** [comment]
i’ll have a fix out sometime soon
