### ISSUE TITLE
Server wont start with REI installed

### ISSUE THREAD

**Issue by ryanclemente95** [ianm1647/expandeddelight#24]
ExpandedDelight Version: 0.2

I added Modern Industrialization to my server which requires REI to be on the server. After adding both server side, i started the server and came up with this error: https://pastebin.com/0rjwnXYJ

**Comment by ianm1647** [comment]
i’ll look at it soon

**Comment by ianm1647** [comment]
actually you're on 0.2 which had that problem, update your mod
