### ISSUE TITLE
Can't cut cheese or get cinnamon 

### ISSUE THREAD

**Issue by vlad1m** [ianm1647/expandeddelight#33]
The same issue as the previous ones about inability to cut cheese ,playing on fabric 1.18.2 with the latest version of the mod.

**Comment by Traehgniw** [comment]
Playing on Fabric 1.18.2 with the 25th Janurary 2023 version and I noticed that base Farmer's Delight knives could not cut cheese. A Farmer's Knives copper knife did work.
