### ISSUE TITLE
can't break salt ore.

### ISSUE THREAD

**Issue by electricsteve** [ianm1647/expandeddelight#41]
i cant break salt ore.

**Comment by linkbeta5** [comment]
Same, and can't seem to find a solution for it.

**Comment by electricsteve** [comment]
> Same, and can't seem to find a solution for it.

I found a fix. I made a custom datapack which give the block the "mineable/pickaxe" tag (i think, im not at my pc to check). That makes it work. So they just have to add the tag to the block.

**Comment by MinuteLicence** [comment]
> I found a fix. I made a custom datapack which give the block the "mineable/pickaxe" tag (i think, im not at my pc to check). That makes it work. So they just have to add the tag to the block.

Please may you share the pack? I've tried making one but its not letting players break the ore

**Comment by electricsteve** [comment]
I'm not at my pc rn, but you probably didn't put "minecraft" as the namespace.

**Comment by Ciyuzuna** [comment]
Note: This is for 1.19.2

This was really annoying me so I figured out how to make a datapack to fix it.
I've literally never made a datapack before and I'm not very good at coding in general.
That being said, here's the file that I used to fix the issue for me.

[Salt Ore Fix.zip](https://github.com/ianm1647/expandeddelight/files/10786905/Salt.Ore.Fix.zip)

Unzip the folder into your datapacks folder and restart your game and server.

For single player it should be /minecraft/saves/***YOUR WORLD NAME HERE***/datapacks/ <-extract zip here
For servers /world/datapacks/ <-extract zip here

**Comment by electricsteve** [comment]
Yea, I'm on 1.19.2 myself.
