### ISSUE TITLE
JEI Not showing up

### ISSUE THREAD

**Issue by jting02** [ianm1647/expandeddelight#53]
when using these:

[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Motschen's Better Leaves (by Motschen)](https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves)
[Better Dogs (by mrblueyeti)](https://www.curseforge.com/minecraft/texture-packs/better-dogs)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Presence Footsteps [Fabric] (by S0llace)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps)
[Puzzle (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/puzzle)
[Friends&Foes - Flowery Mooblooms (Fabric) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-flowery-mooblooms-fabric)
[CTOV - Friends and Foes compatibility pack (by ChoiceTheorem)](https://www.curseforge.com/minecraft/texture-packs/ctov-friends-and-foes-compat)
[RightClickHarvest (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Enhanced Boss Bars (by Nakuring)](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars)
[Better Chickens (by mrblueyeti)](https://www.curseforge.com/minecraft/texture-packs/better-chickens)
[Visual Enchantments (by SiscuLog)](https://www.curseforge.com/minecraft/texture-packs/visual-enchantments)
[Expanded Delight [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/expanded-delight)
[Better Farm Animals (by mrblueyeti)](https://www.curseforge.com/minecraft/texture-packs/better-farm-animals)
[Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[JamLib (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/jamlib)
[Medieval Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/medieval-music)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[CIT Resewn (by SHsuperCM)](https://www.curseforge.com/minecraft/mc-mods/cit-resewn)
[Fabric Seasons: Terralith Compat (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons-terralith-compat)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[CTOV - Farmer Delight Compatibility pack (by ChoiceTheorem)](https://www.curseforge.com/minecraft/texture-packs/ctov-farmer-delight-compat)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[WTHIT (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[Dark Paintings (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-paintings)
[Bountiful (Fabric) (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric)
[Friends&Foes - Beekeeper Hut (Fabric) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-beekeeper-hut-fabric)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Repurposed Structures - Friends and Foes Compat Datapack (by telepathicgrunt)](https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-friends-and-foes-datapack)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
[Fabric Seasons: Delight Compat (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons-delight-compat)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[Bigger Better End Cities (by TheArchitects777)](https://www.curseforge.com/minecraft/mc-mods/bigger-better-end-cities)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
[Better Animations Collection (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-animations-collection)
[Diagonal Fences [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)
[Axolotl Bucket Fix (by colderlavalamp)](https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Inventory Sorting (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Fabric Seasons (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Eating Animation [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[Friends&Foes (Fabric) (by faboslav)](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Kiwi 🥝 (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/kiwi-fabric)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Dramatic Doors (by FizzWare)](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors)
[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Blur (Fabric) (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/blur-fabric)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Better Cats (by mrblueyeti)](https://www.curseforge.com/minecraft/texture-packs/better-cats-minecraft)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Tips (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tips)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Dusk[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dusk)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Lapis Reserve (by sfort__)](https://www.curseforge.com/minecraft/mc-mods/lapis-reserve)
[Visuality (by PinkGoosik)](https://www.curseforge.com/minecraft/mc-mods/visuality)
[Repurposed Structures - Bountiful Compat Datapack (by telepathicgrunt)](https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-bountiful-datapack-compat)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Dehydration (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/dehydration)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Recipe Book Delight (by melontini)](https://www.curseforge.com/minecraft/mc-mods/recipe-book-delight)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[CompleteConfig (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/completeconfig)
[Grizzly bear Mod - Fabric (by Aquatic)](https://www.curseforge.com/minecraft/mc-mods/grizzly-bear)
[Stay True (by haimcyfly)](https://www.curseforge.com/minecraft/texture-packs/stay-true)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Dehydration Expanded Drinks (by MuonR)](https://www.curseforge.com/minecraft/texture-packs/dehydration-expanded-drinks)
[Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
[Custom Entity Models (CEM) (by dorianpb)](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Snow! Real Magic! ⛄ (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)

def ur mod tho

**Comment by ianm1647** [comment]
i havent added jei support

**Comment by ianm1647** [comment]
only rei, jei is a future goal, same with emi
