### ISSUE TITLE
Incompatibility with JEI

### ISSUE THREAD

**Issue by DEAFG0AT** [ianm1647/expandeddelight#57]
Hello there, I am using Fabric 1.19.2 expanded delight and the recipes for expanded delight meals don't show up in JEI. Also when you try to see the recipe or uses of a certain food/item there are no uses listed in JEI

**Comment by ianm1647** [comment]
> Hello there, I am using Fabric 1.19.2 expanded delight and the recipes for expanded delight meals don't show up in JEI. Also when you try to see the recipe or uses of a certain food/item there are no uses listed in JEI

if you are using jei, there is no jei support, the only support is rei, this also applies to farmers delight fabric, it does not support jei
