### ISSUE TITLE
Server automatically disconnects

### ISSUE THREAD

**Issue by TheButterbrotMan** [ianm1647/expandeddelight#6]
Hello, singleplayer is working.

When i open a local server and trying to connect there i get instantly disconnected.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/3s7ni4Slba

**Comment by TheButterbrotMan** [comment]
[sdad-DEV.zip](https://github.com/ianm1647/expandeddelight/files/8794443/sdad-DEV.zip)
Thats the Instance

**Comment by TheButterbrotMan** [comment]
0.1.4 was working.

**Comment by ianm1647** [comment]
are you sure this is expandeddelight
because it doesnt mention it in the log at all

**Comment by TheButterbrotMan** [comment]
I am sure. I did remove mods by hand, one by one.

**Comment by Daturachan** [comment]
Exactly the same issue for me. I've also pinned this down to Expanded Delight.

0.1.4 works fine, but 0.1.5 causes a "Connection Lost" error every single time.

**Comment by Footage2-Amply-Pounce** [comment]
Can confirm as well. Tested with only Farmer's Delight + Expanded Delight on a dedicated server. There are some errors in the logs related to Expanded Delight, but I don't know if they are responsible for the connectivity issue: https://gist.github.com/Footage2-Amply-Pounce/c0ea44151989e365d6666518a16406f7

**Comment by TheAlmightyBreadbear** [comment]
I am also having this issue. Haven't tested with just the mod, but continues to occur with other mods.

**Comment by Ironchestplate** [comment]
I can concur that It was the pepper portion of the new Expanded Delight update that caused AQM2 to crash

**Comment by itsdinkd** [comment]
> are you sure this is expandeddelight because it doesnt mention it in the log at all

This just happened on our official servers for the last 8 hours. It didn't generate anything in the logs, no error on the screen, I binary searched numerous mods that I updated today. After removing expanded delight, the disconnect went away. This only happens on the new update you pushed, the one prior was fine.

**Comment by ianm1647** [comment]
hopefully the update i pushed out fixes it , im not sure why it was crashing

**Comment by Footage2-Amply-Pounce** [comment]
Actually, nevermind, something went wrong with the CurseForge upload? There's now another 0.1.6 file and that one works.

**Comment by ianm1647** [comment]
> Actually, nevermind, something went wrong with the CurseForge upload? There's now another 0.1.6 file and that one works.

server works now? okay good

**Comment by TheButterbrotMan** [comment]
How did you fix it?

**Comment by ianm1647** [comment]
> How did you fix it?

honestly no idea, i just went through the git push and changed everything back to how it was before and updated the json files that were erroring, the chili pepper crop json still errors but it shouldnt cause any crashing, it was something in the code
