### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [ianm1647/expandeddelight#72]
Add compat for the new port of farmer's delight on fabric

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated

**Comment by aninusmuffin** [comment]
Some context:

> Q. How does this different from the other existing Farmer's Delight Fabric?
> 
> A. This port's main focus has been on simplicity and faithfulness to the original mod. This meant that only minor changes were made to accommodate the loader specific things.
> 
> Package names and all existing behavior has been kept the same. This means that FD addons can now easily be ported from Forge to Fabric with, ideally, no change at all as all the package names are the same.
> 
> [A list of differences can be found here.](https://gist.github.com/MerchantPug/f71b4d89272f8dc3757f4cec723617c0)

**Comment by Killercrab432** [comment]
Why is this post closed when it still does not let me use these together?
