### ISSUE TITLE
Cheese from air

### ISSUE THREAD

**Issue by Laifsyn** [ianm1647/expandeddelight#9]
![image](https://user-images.githubusercontent.com/99366187/171871195-2353c551-3e1a-48c1-9182-8dda34f3b47d.png)

**Comment by Laifsyn** [comment]
The pinnacle of alchemy

**Comment by ianm1647** [comment]
i love it , did that just happen though? or did you do something for it to

**Comment by ianm1647** [comment]
i plan on removing the cooler next update anyway, it doesnt work for me

**Comment by Laifsyn** [comment]
Hi sorry for not coming back sooner. I didn't change anything
